first_name=input("enter your first name: ")
m_i=input("enter your middle initial name: ")
last_name=input("enter your last name: ")
s_a=input("enter your street address: ")
city=input("enter your city: ")
s_z_c=input("enter your state zip code: ")
p_n=input("enter your phone number: ")
e_a=input("enter your email address: ")
print(f"{first_name} {m_i} {last_name}")
print(f"{s_a}, {city} {s_z_c}") 
print(f"{p_n}")
print(f"{e_a}")
